add_newline = false

[package]
disabled = true

[directory]
style = "bold blue"

[git_branch]
style = "bold green"

[git_state]
disabled = true

[git_status]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true
