add_newline = false

[package]
disabled = true

[directory]
style = "bold #00008b"

[git_branch]
style = "bold #228b22"

[git_state]
disabled = true

[git_status]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[gcloud]
format = "(on $symbol[$account@$domain]($style))"
